AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Code Pipeline Slack Notifier

Parameters:
  SlackUrl:
    AllowedPattern : ".+"
    Type: String

Metadata:
  AWS::ServerlessRepo::Application:
    Name: CodePipelineSlackNotifier
    Description: Post notifications to Slack when Code Pipeline Events occur
    Author: Symphonia
    HomePageUrl: https://github.com/symphoniacloud/code-pipeline-slack-notifier
    SourceCodeUrl: https://github.com/symphoniacloud/code-pipeline-slack-notifier
    ReadmeUrl: README.md
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE
    Labels:
      - CodePipeline
      - Slack
    SemanticVersion: 1.0.4

Resources:
  CPLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lib/index.handler
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 10
      CodeUri: ./target/lambda.zip
      Environment:
        Variables:
          SLACK_URL:
            Ref: SlackUrl
      Events:
        CodePipelineEvent:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
              - aws.codepipeline
              detail-type:
              - CodePipeline Pipeline Execution State Change
